version: '3'
services:
  feature_engineering:
    container_name: feature_engineering
    build:
      context: ./feature_engineering
      dockerfile: Dockerfile
    volumes:
      - ./src/feature_engineering:/app
      - ./src/utils:/app/utils
      - ./data:/app/data
    working_dir: /app
    command: ["python3", "main.py"]
    # command: ["python3", "clean_feature_store.py"]
    # command: ["tail", "-f", "/dev/null"]
    networks:
      - fe-nic

  model_training:
    container_name: model_training
    build:
      context: ./model_training
      dockerfile: Dockerfile
    volumes:
      - ./src/model_training:/app
      - ./src/utils:/app/utils
      - ./data:/app/data
    working_dir: /app
    # command: ["python3", "arima.py"]
    command: ["python3", "deploy.py"]
    networks:
      - fe-nic
    # depends_on:
    #   - feature_engineering


volumes:
  data:
    driver: local
  dags:
    driver: local
networks:
  fe-nic:
