version: '3'
services:
  feature_engineering:
    container_name: feature_engineering
    build:
      context: ./feature_engineering
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src/feature_engineering:/app
      - ./src/utils:/app/utils
      - ./data:/app/data
    working_dir: /app
    command: ["python3", "main.py"]
    # command: ["tail", "-f", "/dev/null"]
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    networks:
      - fe-nic

volumes:
  data:
    driver: local
  dags:
    driver: local
networks:
  fe-nic:
